// 2025-02-25 17:35

const inArg = $arguments;
const boolArg = (v, d = false) => {
  if (v == null || v === "") return d;
  return /^(true|1|on|yes)$/i.test(v) ? true : /^(false|0|off|no)$/i.test(v) ? false : !!v;
};

const config = {
  clear: boolArg(inArg.clear, true),
  flag:  boolArg(inArg.flag, true),
  fgf:   inArg.fgf ? decodeURI(inArg.fgf) : " ",
};

const RE_CLEAR = /(GB|TB|免费|套餐|到期|剩余|过期|测试|官网|订阅|流量|机场|联系|客服|有效|重置|网站|地址)/i;
const RE_HOME = /(家宽|住宅|ISP|Home|Residential)/i;

const REGIONS = [
  { re: /\bHK\b|Hong\s?Kong/i, name: "香港", emoji: "🇭🇰" },
  { re: /\bTW\b|Taiwan/i, name: "台湾", emoji: "🇨🇳" },
  { re: /\bMO\b|Macao/i, name: "澳门", emoji: "🇲🇴" },
  { re: /\bJP\b|Japan/i, name: "日本", emoji: "🇯🇵" },
  { re: /\bKR\b|Korea/i, name: "韩国", emoji: "🇰🇷" },
  { re: /\bSG\b|Singapore/i, name: "新加坡", emoji: "🇸🇬" },
  { re: /\bUS\b|USA|United\s?States/i, name: "美国", emoji: "🇺🇸" },
  { re: /\bUK\b|United\s?Kingdom|Britain/i, name: "英国", emoji: "🇬🇧" },
  { re: /\bVN\b|Vietnam/i, name: "越南", emoji: "🇻🇳" },
  { re: /\bDE\b|Germany/i, name: "德国", emoji: "🇩🇪" },
  { re: /\bFR\b|France/i, name: "法国", emoji: "🇫🇷" },
  { re: /\bRU\b|Russia/i, name: "俄罗斯", emoji: "🇷🇺" },
  { re: /\bTH\b|Thailand/i, name: "泰国", emoji: "🇹🇭" },
  { re: /\bPH\b|Philippines/i, name: "菲律宾", emoji: "🇵🇭" },
  { re: /\bMY\b|Malaysia/i, name: "马来西亚", emoji: "🇲🇾" },
  { re: /\bTR\b|Turkey/i, name: "土耳其", emoji: "🇹🇷" },
  { re: /\bIN\b|India/i, name: "印度", emoji: "🇮🇳" },
  { re: /\bID\b|Indonesia/i, name: "印尼", emoji: "🇮🇩" },
  { re: /\bIL\b|Israel/i, name: "以色列", emoji: "🇮🇱" },
  { re: /\bAM\b|Armenia/i, name: "亚美尼亚", emoji: "🇦🇲" },
  { re: /\bAU\b|Australia/i, name: "澳大利亚", emoji: "🇦🇺" },
  { re: /\bNZ\b|New\s?Zealand/i, name: "新西兰", emoji: "🇳🇿" },
  { re: /\bCA\b|Canada/i, name: "加拿大", emoji: "🇨🇦" },
  { re: /\bMX\b|Mexico/i, name: "墨西哥", emoji: "🇲🇽" },
  { re: /\bBR\b|Brazil/i, name: "巴西", emoji: "🇧🇷" },
  { re: /\bAR\b|Argentina/i, name: "阿根廷", emoji: "🇦🇷" },
  { re: /\bCL\b|Chile/i, name: "智利", emoji: "🇨🇱" },
  { re: /\bCO\b|Colombia/i, name: "哥伦比亚", emoji: "🇨🇴" },
  { re: /\bPE\b|Peru/i, name: "秘鲁", emoji: "🇵🇪" },
  { re: /\bIT\b|Italy/i, name: "意大利", emoji: "🇮🇹" },
  { re: /\bES\b|Spain/i, name: "西班牙", emoji: "🇪🇸" },
  { re: /\bNL\b|Netherlands/i, name: "荷兰", emoji: "🇳🇱" },
  { re: /\bCH\b|Switzerland/i, name: "瑞士", emoji: "🇨🇭" },
  { re: /\bSE\b|Sweden/i, name: "瑞典", emoji: "🇸🇪" },
  { re: /\bNO\b|Norway/i, name: "挪威", emoji: "🇳🇴" },
  { re: /\bDK\b|Denmark/i, name: "丹麦", emoji: "🇩🇰" },
  { re: /\bFI\b|Finland/i, name: "芬兰", emoji: "🇫🇮" },
  { re: /\bAT\b|Austria/i, name: "奥地利", emoji: "🇦🇹" },
  { re: /\bBE\b|Belgium/i, name: "比利时", emoji: "🇧🇪" },
  { re: /\bIE\b|Ireland/i, name: "爱尔兰", emoji: "🇮🇪" },
  { re: /\bPT\b|Portugal/i, name: "葡萄牙", emoji: "🇵🇹" },
  { re: /\bGR\b|Greece/i, name: "希腊", emoji: "🇬🇷" },
  { re: /\bCZ\b|Czech/i, name: "捷克", emoji: "🇨🇿" },
  { re: /\bPL\b|Poland/i, name: "波兰", emoji: "🇵🇱" },
  { re: /\bUA\b|Ukraine/i, name: "乌克兰", emoji: "🇺🇦" },
  { re: /\bRO\b|Romania/i, name: "罗马尼亚", emoji: "🇷🇴" },
  { re: /\bHU\b|Hungary/i, name: "匈牙利", emoji: "🇭🇺" },
  { re: /\bAE\b|UAE|United\s?Arab\s?Emirates/i, name: "阿联酋", emoji: "🇦🇪" },
  { re: /\bSA\b|Saudi\s?Arabia/i, name: "沙特", emoji: "🇸🇦" },
  { re: /\bZA\b|South\s?Africa/i, name: "南非", emoji: "🇿🇦" },
  { re: /\bEG\b|Egypt/i, name: "埃及", emoji: "🇪🇬" },
  { re: /\bKH\b|Cambodia/i, name: "柬埔寨", emoji: "🇰🇭" },
  { re: /\bMM\b|Myanmar/i, name: "缅甸", emoji: "🇲🇲" },
  { re: /\bLA\b|Laos/i, name: "老挝", emoji: "🇱🇦" },
  { re: /\bPK\b|Pakistan/i, name: "巴基斯坦", emoji: "🇵🇰" },
  { re: /\bKZ\b|Kazakhstan/i, name: "哈萨克斯坦", emoji: "🇰🇿" },
  { re: /\bUZ\b|Uzbekistan/i, name: "乌兹别克斯坦", emoji: "🇺🇿" },
  { re: /\bJO\b|Jordan/i, name: "约旦", emoji: "🇯🇴" },
  { re: /\bQA\b|Qatar/i, name: "卡塔尔", emoji: "🇶🇦" },
  { re: /\bKW\b|Kuwait/i, name: "科威特", emoji: "🇰🇼" },
  { re: /\bBD\b|Bangladesh/i, name: "孟加拉", emoji: "🇧🇩" },
  { re: /\bLK\b|Sri\s?Lanka/i, name: "斯里兰卡", emoji: "🇱🇰" },
  { re: /\bNP\b|Nepal/i, name: "尼泊尔", emoji: "🇳🇵" },
  { re: /\bMN\b|Mongolia/i, name: "蒙古", emoji: "🇲🇳" },
  { re: /\bMV\b|Maldives/i, name: "马尔代夫", emoji: "🇲🇻" },
  { re: /\bBT\b|Bhutan/i, name: "不丹", emoji: "🇧🇹" },
  { re: /\bBN\b|Brunei/i, name: "文莱", emoji: "🇧🇳" },
  { re: /\bAF\b|Afghanistan/i, name: "阿富汗", emoji: "🇦🇫" },
  { re: /\bIQ\b|Iraq/i, name: "伊拉克", emoji: "🇮🇶" },
  { re: /\bLB\b|Lebanon/i, name: "黎巴嫩", emoji: "🇱🇧" },
  { re: /\bYE\b|Yemen/i, name: "也门", emoji: "🇾🇪" },
  { re: /\bOM\b|Oman/i, name: "阿曼", emoji: "🇴🇲" },
  { re: /\bBH\b|Bahrain/i, name: "巴林", emoji: "🇧🇭" },
  { re: /\bGE\b|Georgia/i, name: "格鲁吉亚", emoji: "🇬🇪" },
  { re: /\bAZ\b|Azerbaijan/i, name: "阿塞拜疆", emoji: "🇦🇿" },
  { re: /\bTM\b|Turkmenistan/i, name: "土库曼斯坦", emoji: "🇹🇲" },
  { re: /\bTJ\b|Tajikistan/i, name: "塔吉克斯坦", emoji: "🇹🇯" },
  { re: /\bKG\b|Kyrgyzstan/i, name: "吉尔吉斯斯坦", emoji: "🇰🇬" },
  { re: /\bCY\b|Cyprus/i, name: "塞浦路斯", emoji: "🇨🇾" },
  { re: /\bIS\b|Iceland/i, name: "冰岛", emoji: "🇮🇸" },
  { re: /\bLU\b|Luxembourg/i, name: "卢森堡", emoji: "🇱🇺" },
  { re: /\bSK\b|Slovakia/i, name: "斯洛伐克", emoji: "🇸🇰" },
  { re: /\bBG\b|Bulgaria/i, name: "保加利亚", emoji: "🇧🇬" },
  { re: /\bHR\b|Croatia/i, name: "克罗地亚", emoji: "🇭🇷" },
  { re: /\bSI\b|Slovenia/i, name: "斯洛文尼亚", emoji: "🇸🇮" },
  { re: /\bEE\b|Estonia/i, name: "爱沙尼亚", emoji: "🇪🇪" },
  { re: /\bLV\b|Latvia/i, name: "拉脱维亚", emoji: "🇱🇻" },
  { re: /\bLT\b|Lithuania/i, name: "立陶宛", emoji: "🇱🇹" },
  { re: /\bBY\b|Belarus/i, name: "白俄罗斯", emoji: "🇧🇾" },
  { re: /\bMD\b|Moldova/i, name: "摩尔多瓦", emoji: "🇲🇩" },
  { re: /\bAL\b|Albania/i, name: "阿尔巴尼亚", emoji: "🇦🇱" },
  { re: /\bBA\b|Bosnia/i, name: "波黑", emoji: "🇧🇦" },
  { re: /\bME\b|Montenegro/i, name: "黑山", emoji: "🇲🇪" },
  { re: /\bMK\b|Macedonia/i, name: "北马其顿", emoji: "🇲🇰" },
  { re: /\bMT\b|Malta/i, name: "马耳他", emoji: "🇲🇹" },
  { re: /\bMC\b|Monaco/i, name: "摩纳哥", emoji: "🇲🇨" },
  { re: /\bAD\b|Andorra/i, name: "安道尔", emoji: "🇦🇩" },
  { re: /\bLI\b|Liechtenstein/i, name: "列支敦士登", emoji: "🇱🇮" },
  { re: /\bSM\b|San\s?Marino/i, name: "圣马力诺", emoji: "🇸🇲" },
  { re: /\bVA\b|Vatican/i, name: "梵蒂冈", emoji: "🇻🇦" },
  { re: /\bIM\b|Isle\s?of\s?Man/i, name: "马恩岛", emoji: "🇮🇲" },
  { re: /\bJE\b|Jersey/i, name: "泽西岛", emoji: "🇯🇪" },
  { re: /\bGG\b|Guernsey/i, name: "根西岛", emoji: "🇬🇬" },
  { re: /\bFO\b|Faroe/i, name: "法罗群岛", emoji: "🇫🇴" },
  { re: /\bGI\b|Gibraltar/i, name: "直布罗陀", emoji: "🇬🇮" },
  { re: /\bGL\b|Greenland/i, name: "格陵兰", emoji: "🇬🇱" },
  { re: /\bPA\b|Panama/i, name: "巴拿马", emoji: "🇵🇦" },
  { re: /\bCR\b|Costa\s?Rica/i, name: "哥斯达黎加", emoji: "🇨🇷" },
  { re: /\bGT\b|Guatemala/i, name: "危地马拉", emoji: "🇬🇹" },
  { re: /\bHN\b|Honduras/i, name: "洪都拉斯", emoji: "🇭🇳" },
  { re: /\bSV\b|Salvador/i, name: "萨尔瓦多", emoji: "🇸🇻" },
  { re: /\bNI\b|Nicaragua/i, name: "尼加拉瓜", emoji: "🇳🇮" },
  { re: /\bCU\b|Cuba/i, name: "古巴", emoji: "🇨🇺" },
  { re: /\bDO\b|Dominican/i, name: "多米尼加", emoji: "🇩🇴" },
  { re: /\bPR\b|Puerto\s?Rico/i, name: "波多黎各", emoji: "🇵🇷" },
  { re: /\bJM\b|Jamaica/i, name: "牙买加", emoji: "🇯🇲" },
  { re: /\bTT\b|Trinidad/i, name: "特立尼达和多巴哥", emoji: "🇹🇹" },
  { re: /\bBS\b|Bahamas/i, name: "巴哈马", emoji: "🇧🇸" },
  { re: /\bBB\b|Barbados/i, name: "巴巴多斯", emoji: "🇧🇧" },
  { re: /\bLC\b|Saint\s?Lucia/i, name: "圣卢西亚", emoji: "🇱🇨" },
  { re: /\bGD\b|Grenada/i, name: "格林纳达", emoji: "🇬🇩" },
  { re: /\bUY\b|Uruguay/i, name: "乌拉圭", emoji: "🇺🇾" },
  { re: /\bPY\b|Paraguay/i, name: "巴拉圭", emoji: "🇵🇾" },
  { re: /\bBO\b|Bolivia/i, name: "玻利维亚", emoji: "🇧🇴" },
  { re: /\bEC\b|Ecuador/i, name: "厄瓜多尔", emoji: "🇪🇨" },
  { re: /\bVE\b|Venezuela/i, name: "委内瑞拉", emoji: "🇻🇪" },
  { re: /\bGY\b|Guyana/i, name: "圭亚那", emoji: "🇬🇾" },
  { re: /\bSR\b|Suriname/i, name: "苏里南", emoji: "🇸🇷" },
  { re: /\bDZ\b|Algeria/i, name: "阿尔及利亚", emoji: "🇩🇿" },
  { re: /\bMA\b|Morocco/i, name: "摩洛哥", emoji: "🇲🇦" },
  { re: /\bTN\b|Tunisia/i, name: "突尼斯", emoji: "🇹🇳" },
  { re: /\bLY\b|Libya/i, name: "利比亚", emoji: "🇱🇾" },
  { re: /\bNG\b|Nigeria/i, name: "尼日利亚", emoji: "🇳🇬" },
  { re: /\bGH\b|Ghana/i, name: "加纳", emoji: "🇬🇭" },
  { re: /\bKE\b|Kenya/i, name: "肯尼亚", emoji: "🇰🇪" },
  { re: /\bTZ\b|Tanzania/i, name: "坦桑尼亚", emoji: "🇹🇿" },
  { re: /\bUG\b|Uganda/i, name: "乌干达", emoji: "🇺🇬" },
  { re: /\bET\b|Ethiopia/i, name: "埃塞俄比亚", emoji: "🇪🇹" },
  { re: /\bSD\b|Sudan/i, name: "苏丹", emoji: "🇸🇩" },
  { re: /\bCI\b|Ivory\s?Coast/i, name: "科特迪瓦", emoji: "🇨🇮" },
  { re: /\bCM\b|Cameroon/i, name: "喀麦隆", emoji: "🇨🇲" },
  { re: /\bAO\b|Angola/i, name: "安哥拉", emoji: "🇦🇴" },
  { re: /\bZM\b|Zambia/i, name: "赞比亚", emoji: "🇿🇲" },
  { re: /\bZW\b|Zimbabwe/i, name: "津巴布韦", emoji: "🇿🇼" },
  { re: /\bBW\b|Botswana/i, name: "博茨瓦纳", emoji: "🇧🇼" },
  { re: /\bNA\b|Namibia/i, name: "纳米比亚", emoji: "🇳🇦" },
  { re: /\bMG\b|Madagascar/i, name: "马达加斯加", emoji: "🇲🇬" },
  { re: /\bRS\b|Serbia/i, name: "塞尔维亚", emoji: "🇷🇸" },
  { re: /\bKP\b|North\s?Korea|Korea\s?DPR/i, name: "朝鲜", emoji: "🇰🇵" },
  { re: /\bSY\b|Syria/i, name: "叙利亚", emoji: "🇸🇾" },
  { re: /\bTL\b|Timor/i, name: "东帝汶", emoji: "🇹🇱" },
  { re: /\bCF\b|Central\s?African/i, name: "中非共和国", emoji: "🇨🇫" },
  { re: /\bBZ\b|Belize/i, name: "伯利兹", emoji: "🇧🇿" },
  { re: /\bAG\b|Antigua/i, name: "安提瓜和巴布达", emoji: "🇦🇬" },
  { re: /\bKN\b|Saint\s?Kitts/i, name: "圣基茨和尼维斯", emoji: "🇰🇳" },
  { re: /\bVC\b|Saint\s?Vincent/i, name: "圣文森特和格林纳丁斯", emoji: "🇻🇨" },
  { re: /\bDM\b|Dominica\b/i, name: "多米尼克", emoji: "🇩🇲" },
  { re: /\bCK\b|Cook\s?Islands/i, name: "库克群岛", emoji: "🇨🇰" },
  { re: /\bNU\b|Niue/i, name: "纽埃", emoji: "🇳🇺" },
  { re: /\bXK\b|Kosovo/i, name: "科索沃", emoji: "🇽🇰" },
  { re: /\bAW\b|Aruba/i, name: "阿鲁巴", emoji: "🇦🇼" },
  { re: /\bBM\b|Bermuda/i, name: "百慕大", emoji: "🇧🇲" },
  { re: /\bKY\b|Cayman/i, name: "开曼群岛", emoji: "🇰🇾" },
  { re: /\bCW\b|Curacao/i, name: "库拉索", emoji: "🇨🇼" },
  { re: /\bPF\b|Polynesia/i, name: "法属波利尼西亚", emoji: "🇵🇫" },
  { re: /\bGM\b|Gambia/i, name: "冈比亚", emoji: "🇬🇲" },
  { re: /\bGW\b|Bissau/i, name: "几内亚比绍", emoji: "🇬🇼" },
  { re: /\bLR\b|Liberia/i, name: "利比里亚", emoji: "🇱🇷" },
  { re: /\bMW\b|Malawi/i, name: "马拉维", emoji: "🇲🇼" },
  { re: /\bML\b|Mali/i, name: "马里", emoji: "🇲🇱" },
  { re: /\bMR\b|Mauritania/i, name: "毛里塔尼亚", emoji: "🇲🇷" },
  { re: /\bNE\b|Niger/i, name: "尼日尔", emoji: "🇳🇪" },
  { re: /\bTG\b|Togo/i, name: "多哥", emoji: "🇹🇬" },
  { re: /\bSL\b|Sierra\s?Leone/i, name: "塞拉利昂", emoji: "🇸🇱" },
  { re: /\bVU\b|Vanuatu/i, name: "瓦努阿图", emoji: "🇻🇺" },
  { re: /\bTO\b|Tonga/i, name: "汤加", emoji: "🇹🇴" },
  { re: /\bWS\b|Samoa/i, name: "萨摩亚", emoji: "🇼🇸" },
  { re: /\bSB\b|Solomon/i, name: "所罗门群岛", emoji: "🇸🇧" },
  { re: /\bMU\b|Mauritius/i, name: "毛里求斯", emoji: "🇲🇺" },
  { re: /\bSC\b|Seychelles/i, name: "塞舌尔", emoji: "🇸🇨" },
  { re: /\bSN\b|Senegal/i, name: "塞内加尔", emoji: "🇸🇳" },
  { re: /\bBF\b|Burkina/i, name: "布基纳法索", emoji: "🇧🇫" },
  { re: /\bTD\b|Chad/i, name: "乍得", emoji: "🇹🇩" },
  { re: /\bBJ\b|Benin/i, name: "贝宁", emoji: "🇧🇯" },
  { re: /\bGN\b|Guinea/i, name: "几内亚", emoji: "🇬🇳" },
  { re: /\bGQ\b|Equatorial/i, name: "赤道几内亚", emoji: "🇬🇶" },
  { re: /\bGA\b|Gabon/i, name: "加蓬", emoji: "🇬🇦" },
  { re: /\bCG\b|Congo/i, name: "刚果（布)", emoji: "🇨🇬" },
  { re: /\bCD\b|Kinshasa/i, name: "刚果（金)", emoji: "🇨🇩" },
  { re: /\bMZ\b|Mozambique/i, name: "莫桑比克", emoji: "🇲🇿" },
  { re: /\bCV\b|Cape\s?Verde/i, name: "佛得角", emoji: "🇨🇻" },
  { re: /\bDJ\b|Djibouti/i, name: "吉布提", emoji: "🇩🇯" },
  { re: /\bSO\b|Somalia/i, name: "索马里", emoji: "🇸🇴" },
  { re: /\bFJ\b|Fiji/i, name: "斐济", emoji: "🇫🇯" },
  { re: /\bPG\b|Papua/i, name: "巴布亚新几内亚", emoji: "🇵🇬" },
  { re: /\bGU\b|Guam/i, name: "关岛", emoji: "🇬🇺" },
  { re: /\bNC\b|Caledonia/i, name: "新喀里多尼亚", emoji: "🇳🇨" },
  { re: /\bAQ\b|Antarctica/i, name: "南极洲", emoji: "🇦🇶" },
  { re: /\bPS\b|Palestine/i, name: "巴勒斯坦", emoji: "🇵🇸" },
  { re: /\bRE\b|Reunion/i, name: "留尼汪", emoji: "🇷🇪" },
  { re: /\bMQ\b|Martinique/i, name: "马提尼克", emoji: "🇲🇶" },
  { re: /\bGP\b|Guadeloupe/i, name: "瓜德罗普", emoji: "🇬🇵" },
  { re: /\bYT\b|Mayotte/i, name: "马约特", emoji: "🇾🇹" },
  { re: /\bGF\b|French\s?Guiana/i, name: "法属圭亚那", emoji: "🇬🇫" },
  { re: /\bVG\b|Virgin\s?Islands/i, name: "英属维尔京群岛", emoji: "🇻🇬" },
  { re: /\bVI\b|United\s?States\s?Virgin/i, name: "美属维尔京群岛", emoji: "🇻🇮" },
  { re: /\bTC\b|Turks/i, name: "特克斯和凯科斯", emoji: "🇹🇨" },
  { re: /\bAI\b|Anguilla/i, name: "安圭拉", emoji: "🇦🇮" },
  { re: /\bPM\b|Miquelon/i, name: "圣皮埃尔和密克隆", emoji: "🇵🇲" },
  { re: /\bCN\b|China/i, name: "中国大陆", emoji: "🇨🇳" }
];

function operator(pro) {
  const counts = {};
  return pro
    .filter(p => !(config.clear && RE_CLEAR.test(p.name)))
    .map(p => {
      let matched = REGIONS.find(r => r.re.test(p.name));
      if (!matched) return null;

      const isHome = RE_HOME.test(p.name);
      
      counts[matched.name] = (counts[matched.name] || 0) + 1;
      const num = String(counts[matched.name]).padStart(2, '0');

      const parts = [];
      if (config.flag) parts.push(matched.emoji);
      parts.push(matched.name);
      parts.push(num);
      if (isHome) parts.push("家宽");

      p.name = parts.join(config.fgf);
      return p;
    })
    .filter(p => p !== null);
}
